estimation_frequency: 100
expected_imu_dt: 0.02

Q_acc_x: 0.0001
Q_acc_y: 0.0001
Q_acc_z: 0.0001
Q_angular_x: 0.00001
Q_angular_y: 0.00001
Q_angular_z: 0.00001

pose_p_cov: 0.01
vel_p_cov: 0.001
angle_p_cov: 0.01

p_drift_p_cov: 0.0001
q_drift_p_cov: 0.0001

estimate_acc_bias: true
acc_bias_var: [ 0.001,0.001,0.001]
acc_bias_p_cov: 0.001

estimate_gyro_bias: true
gyro_bias_var: [ 0.001,0.001,0.001]
gyro_bias_p_cov: 0.001

estimate_gravity: true
g: [0,0,-9.81]
g_p_cov: 0.1

#position sensor params
Sensor_prefix: [camera]
initial_sensor: camera

#orbslam3
camera_is_orientation_sensor: true
camera_is_velocity_sensor: false
camera_estimate_drift: true
camera_topic: /orb_slam3/odom
camera_msg_type: 0
camera_R_pose: [0.002, 0.002, 0.001]
camera_R_angle: [0.1, 0.1, 0.1]
camera_rotation: [1,0,0,0,1,0,0,0,1]
camera_translation: [0,0,0]
camera_origin_at_first_measurement: false
camera_position_outlier_lim: [3, 3, 1.5]
camera_orientation_outlier_lim: [0, 0, 0]
