%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV), from camera info topic
# Camera1.fx: 644.939697265625
# Camera1.fy: 643.4590454101562
# Camera1.cx: 655.9939575195312
# Camera1.cy: 361.74267578125

# Camera1.k1: -0.052768804132938385
# Camera1.k2: 0.06145431473851204
# Camera1.p1: -0.00048639930901117623
# Camera1.p2: 0.0011309342226013541
# Camera1.k3: -0.019579153507947922

# From callibration
Camera1.fx: 641.99571579
Camera1.fy: 644.21821602
Camera1.cx: 658.53618072
Camera1.cy: 361.49851635

Camera1.k1: -0.04830575
Camera1.k2: 0.034827119
Camera1.p1: -0.00038049
Camera1.p2: 0.0018345919
Camera1.k3: 0.0

Camera.width: 1280
Camera.height: 720

# Camera frames per second 
Camera.fps: 30

# IR projector baseline times fx (aprox.), fx=613, baseline=95mm
# Realsense D455 IR projector baseline = 95mm
Camera.bf: 58.14

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0
# Stereo.b: 0.07732
Stereo.b: 0.0745

# Depth map values factor
# The depth images are scaled by a factor of 5000, 
# i.e., a pixel value of 5000 in the depth image corresponds to a distance of 1 meter from the camera
# RGBD.DepthMapFactor: 5000.0 # 1.0 for ROS_bag
RGBD.DepthMapFactor: 1000.0
#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
